### ISSUE TITLE
strange axis index in seminstVolume.py

### ISSUE THREAD

**Issue by GITSHOHOKU** [renezurbruegg/SemanticInstanceFusion#1]
Hi, thanks for release this useful repo. 
I noticed that in SemInstVolume.py line #509 #527  using depth_im by the index [pix_y[valid_pts], pix_y[valid_pts]], should it be exchange x and y coordinate, or is there any detail I missed?

**Comment by renezurbruegg** [comment]
Hi

The lines you mentioned, do not match with the code snippet. I assume you mean [#487](https://github.com/renezurbruegg/SemanticInstanceFusion/blob/b35e3fa0e9a9452c810fc27d750070310bf580c6/src/SemInstVolume.py#L487) ?

Some of the code comes from andy zengs tsdf-fusion repository. You can find the same line of code [there](
https://github.com/andyzeng/tsdf-fusion-python/blob/3f22a940d90f684145b1f29b1feaa92e09eb1db6/fusion.py#L265).

Did you try to swap the indices? I think they should match.
Note that for opencv images and numpy arrays, x and y are permuted, which can lead to confusing assignments.

**Comment by GITSHOHOKU** [comment]
Thanks for your reminding.  I look through andy zends repository. Your are right, the PIL image.open different from opencv, it's image x-y axis are  exchanged.
