### ISSUE TITLE
incomplete files in 'Dataset/masks/'

### ISSUE THREAD

**Issue by rex131** [renezurbruegg/SemanticInstanceFusion#4]
I have found the files is not complete in 'Dataset/masks/'. here are some details
![2021-09-22 20-49-07 的屏幕截图](https://user-images.githubusercontent.com/87143368/134346712-94d8b143-85ae-4fa0-8caf-80468c4066ec.png)

there is no a apart of files like 00286, 00318, 00319
is it normal? if so ,why it told me like this : 

'FileNotFoundError: [Errno 2] No such file or directory: 'Dataset/masks/00470''

and

'raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GeneralizedRCNNTransform' object has no attribute 'fixed_size''

looking forward to your reply

**Comment by NicoSchulthess** [comment]
Hi,
there was a small bug in our code and this fix should prevent this issue from happening again. Also, I created masks for all images and uploaded them to the master branch.
