### ISSUE TITLE
question about depth_im

### ISSUE THREAD

**Issue by rex131** [renezurbruegg/SemanticInstanceFusion#6]
I have a very bas problem but it puzzle me for a long time.
i have noticed that your range of the depth_data is 0-3000,  which is in millimeters.
but i cannot find a function which can save the depth data in range 0-3000 as depth image.(it will change the data into 0-255)
could you help me to tell me some ways to save the depth data. i know it is a little stupid, but it will be very kind of you if you can help me.
thank you for your time

**Comment by renezurbruegg** [comment]
Have a look at Pillow and the different Image modes here
https://pillow.readthedocs.io/en/stable/handbook/concepts.html
