### ISSUE TITLE
#Ask about datasets

### ISSUE THREAD

**Issue by duyouzhi** [renezurbruegg/SemanticInstanceFusion#7]
Hello, renezurbruegg and other authors. I am a student and began to have a deep interest in your program in June. At present, I can reproduce your datasets, but I don't know where to start with custom datasets. Therefore, I would like to ask which camera you are using, how to get the pose information, how to get the relevant parameters of the camera, and how to get depth.Thank you very much.

**Comment by renezurbruegg** [comment]
You will need an this information before using our framework. Most datasets (e.g.  [Scannet](http://www.scan-net.org)) provide this.

If you want to use your own data, you will need a RGB-D camera (e.g. Kinect or Realsense) and obtain camera poses using Visual Odometry or other SLAM algorithms. 
You will also need to calibrate your camera to get the intrinsic camera parameters.
